eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
server:
  port: 9001
spring:
  application:
    name: admin-client
#    boot:
#        admin:
#            client:
#                url: http://127.0.0.1:9000
management:
  endpoints:
    web:
      exposure:
        include: "*"
